package com.model.enums;

public enum Region {
    IRELAND_AND_UK,
    NORTHERN_EUROPE,
    BALTICS,
    EASTERN_EUROPE,
    SOUTHEASTERN_EUROPE,
    GREECE,
    BALKANS,
    TURKIYE,
    CENTRAL_EUROPE,
    POLAND,
    GERMANY,
    WESTERN_EUROPE,
    SWITZERLAND,
    FRANCE,
    IBERIA
}
